import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed); 
        double sumChildren = 0;
		int num2Children = 0;
		int num3Children = 0;
		int numManyChildren =0;
		for (int i = 1;i < T ;i++) {
			boolean girl = false; //at list one girl
			boolean boy = false; //at list one girl
			int numChildren = 0;
			while (girl == false || boy == false) {
				double result = generator.nextDouble();
				// System.out.println(result);
				if (result > 0.5) {
					girl = true;
					numChildren += 1;
				} else {
					boy = true;
					numChildren += 1;
				}
				if (numChildren == 2) {
					num2Children += 1;
				}else if (numChildren == 3) {
					num3Children += 1;
				}else if (numChildren > 3) {
					numManyChildren += 1;
					}
				}
				sumChildren += numChildren;
			}
		double avreage = sumChildren/ T;
		System.out.println("Average: " + avreage + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + num2Children);
		System.out.println("Number of families with 3 children: " + num3Children);
		System.out.println("Number of families with 4 or more children: " + numManyChildren);
		if (num2Children > num3Children && num2Children > numManyChildren) {
			 System.out.println("The most common number of children is 2.");
		}else if (num3Children > num2Children && num3Children > numManyChildren) {
			 System.out.println("The most common number of children is 3.");
		}else if (numManyChildren > num2Children && numManyChildren > num3Children) {
			 System.out.println("The most common number of children is 4 or more.");
			}
	}
}
 
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		    
	

